apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-ui
  template:
    metadata:
      labels:
        app: chat-ui
    spec:
      containers:
      - name: chat-ui
        image: chat-ui:local  # Use the locally built image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chat-ui-service
spec:
  type: NodePort  # Use NodePort for local access
  selector:
    app: chat-ui
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 300
